# travis.yml

sudo: required
services:
  - docker

env:
  - COMPOSE_VERSION=1.23.1

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

install:
  - docker build --pull --no-cache -t fflo/freeradius .

# Assist with ci test debugging:
#  - DEBUG=1

before_script:
  - image="fflo/freeradius"
  - docker inspect "$image"

script: ./scripts/run-tests.sh

#notifications:
#  email:
#    - fflo@...
